# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    # PHP 8.1+ compatibility
    php_errors:
        log: true

    # Rate limiter configuration
    rate_limiter:
        login:
            policy: sliding_window
            limit: 5
            interval: '1 minute'
        register:
            policy: sliding_window
            limit: 3
            interval: '1 hour'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
