nelmio_api_doc:
    documentation:
        info:
            title: Project Babel API
            version: 1.0.0
            description: Documentation for the versioned Project Babel API
            contact:
                name: Project Babel Team
                email: support@projectbabel.org
            license:
                name: MIT
                url: https://opensource.org/licenses/MIT

    areas:
        default:
            path_patterns: [ '^/api/v1' ]
            documentation:
                info:
                    title: Project Babel API v1
                    version: 1.0.0
                    description: |
                        Documentation for Project Babel API version 1
                        
                        This version includes:
                        - Basic authentication (JWT)
                        - API Key authentication
                        - User registration
                        - User management
                        
                        For more information, visit our documentation at:
                        https://docs.projectbabel.org/api/v1
                components:
                    securitySchemes:
                        bearerAuth:
                            type: http
                            scheme: bearer
                            bearerFormat: JWT
                        apiKeyAuth:
                            type: apiKey
                            in: header
                            name: X-API-Key
                    security:
                        - bearerAuth: []
                        - apiKeyAuth: []
