nelmio_api_doc:
    documentation:
        info:
            title: Project Babel API
            description: Documentation of the Project Babel API
            version: 1.0.0
        paths:
            /api/login:
                post:
                    tags:
                        - Authentication
                    summary: Login to get a JWT token
                    operationId: login
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        email:
                                            type: string
                                            format: email
                                        password:
                                            type: string
                                            format: password
                                    required:
                                        - email
                                        - password
                    responses:
                        '200':
                            description: JWT token
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        '401':
                            description: Invalid credentials
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            message:
                                                type: string
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            security:
                - Bearer: []
    areas:
        path_patterns:
            - ^/api
