api_v1_auth_login:
    path: /api/v1/auth/login
    controller: App\Controller\Api\V1\AuthController::login
    methods: ['POST']

api_v1_auth_register:
    path: /api/v1/auth/register
    controller: App\Controller\Api\V1\AuthController::register
    methods: ['POST'] 