controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# API Routes
api_v1:
    resource: ../src/Controller/Api/V1/
    type: attribute
    prefix: /api/v1

# Swagger UI (versionné)
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: 'nelmio_api_doc.controller.swagger_ui', area: 'default' }

app.swagger_ui_v2:
    path: /api/doc/v2
    methods: GET
    defaults: { _controller: 'nelmio_api_doc.controller.swagger_ui', area: 'v2' }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: 'nelmio_api_doc.controller.swagger', area: 'default' }

app.swagger_v2:
    path: /api/doc/v2.json
    methods: GET
    defaults: { _controller: 'nelmio_api_doc.controller.swagger', area: 'v2' }

api_login_check:
    path: /api/login
    methods: ['POST']
