# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    # Rate limiter storage configuration
    limiter.storage.login:
        class: Symfony\Component\RateLimiter\Storage\CacheStorage
        arguments:
            $pool: '@cache.app'

    limiter.storage.register:
        class: Symfony\Component\RateLimiter\Storage\CacheStorage
        arguments:
            $pool: '@cache.app'

    limiter.storage.api:
        class: Symfony\Component\RateLimiter\Storage\CacheStorage
        arguments:
            $pool: '@cache.app'

    Symfony\Component\RateLimiter\Storage\StorageInterface: '@limiter.storage.login'

    # Rate limiter services
    login.limiter:
        class: Symfony\Component\RateLimiter\RateLimiterFactory
        arguments:
            $config:
                id: 'login'
                policy: 'sliding_window'
                limit: 5
                interval: '1 minute'
            $storage: '@limiter.storage.login'

    register.limiter:
        class: Symfony\Component\RateLimiter\RateLimiterFactory
        arguments:
            $config:
                id: 'register'
                policy: 'fixed_window'
                limit: 3
                interval: '1 hour'
            $storage: '@limiter.storage.register'

    api.limiter:
        class: Symfony\Component\RateLimiter\RateLimiterFactory
        arguments:
            $config:
                id: 'api'
                policy: 'fixed_window'
                limit: 100
                interval: '1 minute'
            $storage: '@limiter.storage.api'

    # Event listener for login rate limiting
    App\EventListener\LoginRateLimitListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 50 }

    App\Security\RateLimiterAuthenticator:
        arguments:
            $limiter: '@api.limiter'
